<p class="main_title">热门车型</p>
            <div class="hot_series">
                <table>
                    <tbody>
                        <tr>
                            <td class="title">SUV</td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=宝马X5"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=366" target="_blank">宝马X5</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=366" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br10/se366.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=丰田普拉多"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/124.html?se=48" target="_blank">丰田普拉多</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/124.html?se=48" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br2/se48.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=本田缤智"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/49.html?se=1550" target="_blank">本田缤智</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/49.html?se=1550" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br9/se1550.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=雪佛兰TRAX创酷"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/119.html?se=1503" target="_blank">雪佛兰TRAX创酷</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/119.html?se=1503" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br57/se1503.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=沃尔沃XC90"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=196" target="_blank">沃尔沃XC90</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=196" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br56/se196.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=雪铁龙C3-XR"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/120.html?se=1915" target="_blank">雪铁龙C3-XR</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/120.html?se=1915" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br58/se1915.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=标致2008"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/30.html?se=1502" target="_blank">标致2008</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/30.html?se=1502" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br8/se1502.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=Jeep自由侠"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/65.html?se=2305" target="_blank">Jeep自由侠</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/65.html?se=2305" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br32/se2305.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=奥迪Q7"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=344" target="_blank">奥迪Q7</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=344" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br19/se344.html" target="_blank">行情</a></td>
                        </tr>
                        <tr>
                            <td class="title">紧凑型</td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=大众速腾"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/123.html?se=365" target="_blank">大众速腾</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/123.html?se=365" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br1/se365.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=大众途观"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/103.html?se=629" target="_blank">大众途观</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/103.html?se=629" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br1/se629.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=宝马X1"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=1208" target="_blank">宝马X1</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=1208" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br10/se1208.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=大众高尔夫"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/123.html?se=9" target="_blank">大众高尔夫</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/123.html?se=9" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br1/se9.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=广汽传祺GS4"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/50.html?se=2036" target="_blank">广汽传祺GS4</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/50.html?se=2036" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br68/se2036.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=福特福克斯"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/19.html?se=287" target="_blank">福特福克斯</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/19.html?se=287" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br3/se287.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=奥迪Q3"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=1536" target="_blank">奥迪Q3</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=1536" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br19/se1536.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=丰田卡罗拉"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/124.html?se=442" target="_blank">丰田卡罗拉</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/124.html?se=442" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br2/se442.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=日产轩逸"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/34.html?se=382" target="_blank">日产轩逸</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/34.html?se=382" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br49/se382.html" target="_blank">行情</a></td>
                        </tr>
                        
                        <tr>
                            <td class="title">中型车</td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=宝马3系"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=95" target="_blank">宝马3系</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=95" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br10/se95.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=奥迪A4L"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=5" target="_blank">奥迪A4L</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=5" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br19/se5.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=奥迪Q5"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=658" target="_blank">奥迪Q5</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=658" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br19/se658.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=大众迈腾"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/123.html?se=410" target="_blank">大众迈腾</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/123.html?se=410" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br1/se410.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=沃尔沃XC60"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=1989" target="_blank">沃尔沃XC60</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=1989" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br56/se1989.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=广汽传祺GS8"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/50.html?se=2334" target="_blank">广汽传祺GS8</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/50.html?se=2334" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br68/se2334.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=丰田汉兰达"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/51.html?se=581" target="_blank">丰田汉兰达</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/51.html?se=581" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br2/se581.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=福特锐界"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/19.html?se=2001" target="_blank">福特锐界</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/19.html?se=2001" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br3/se2001.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=本田雅阁"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/49.html?se=72" target="_blank">本田雅阁</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/49.html?se=72" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br9/se72.html" target="_blank">行情</a></td>
                        </tr>
                        
                        <tr>
                            <td class="title">豪华型</td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=宝马5系"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=131" target="_blank">宝马5系</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=131" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br10/se131.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=奥迪A6L"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=6" target="_blank">奥迪A6L</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/1.html?se=6" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br19/se6.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=奔驰E级"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/12.html?se=312" target="_blank">奔驰E级</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/12.html?se=312" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br22/se312.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=宝马7系"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=290" target="_blank">宝马7系</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/4.html?se=290" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br10/se290.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=雷克萨斯ES"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/81.html?se=379" target="_blank">雷克萨斯ES</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/81.html?se=379" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br38/se379.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=奔驰S级"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/12.html?se=260" target="_blank">奔驰S级</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/12.html?se=260" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br22/se260.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=沃尔沃V60"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=1115" target="_blank">沃尔沃V60</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=1115" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br56/se1115.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=沃尔沃S80L"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=579" target="_blank">沃尔沃S80L</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/115.html?se=579" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br56/se579.html" target="_blank">行情</a></td>
                            <td zhugeiomc="团购首页v3.0.1_品牌墙下方车系墙点击|品牌=丰田皇冠"><a class="n" href="http://www.miaoche.com/chengdu/tuan/br/124.html?se=124" target="_blank">丰田皇冠</a><a class="t" href="http://www.miaoche.com/chengdu/tuan/br/124.html?se=124" target="_blank">团购</a><a class="s" href="http://www.miaoche.com/chengdu/search/br2/se124.html" target="_blank">行情</a></td>
                        </tr>
                </tbody>
                </table>
            </div>